### ISSUE TITLE
[Bug]: Dependency issues with Tabulate 9.0 causes Snakemake 7.14.0 to misbehave

### ISSUE THREAD

**Issue by karen-Gg** [friendsofstrandseq/mosaicatcher-pipeline#23]
### What happened?

An update to tabulate causes an error with snakemake, which has been resolved in snakemake 7.15.2 (see here for more info https://github.com/snakemake/snakemake/issues/1899). 

To use snakemake 7.14.0 (per the current conda environment recommendations), downgrading tabulate from 9.0 to 8.10 via 
mamba install 'tabulate=0.8.10'
allows the dry-run to proceed as expected

### Steps To Reproduce

(using Ubuntu 20.4 fresh VM, not EMBL infrastructure)

conda install -c conda-forge mamba
conda config --set channel_priority flexible
mamba create -n snakemake -c bioconda -c conda-forge -c defaults -c anaconda snakemake=7.14.0
mamba init
mamba activate snakemake
conda config --set channel_priority strict
git clone --recurse-submodules https://github.com/friendsofstrandseq/mosaicatcher-pipeline.git && cd mosaicatcher-pipeline

snakemake --configfile .tests/config/simple_config.yaml --config ashleys_pipeline=True --use-conda --latency-wait 120 --notemp --forceall --cores 1 -n

### Mosaicatcher-pipeline Version

1.5.1 (Default)

### Command used

```shell
snakemake --configfile .tests/config/simple_config.yaml --config ashleys_pipeline=True --use-conda --latency-wait 120 --notemp --forceall --cores 1 -n
```

### How did you run the pipeline?

Conda only

### What did you use to run the pipeline? (local execution, HPC, cloud)

local execution

### Pipeline configuration file

```YAML
.tests/config/simple_config.yaml


version: 1.8.5
ashleys_pipeline_version: 1.3.5
#######################################
#   MOSAICATCHER CONFIGURATION FILE.  #
#######################################

email: ""

#######################################
## Command-line options
#######################################

# ashleys-qc pipeline arguments
mosaicatcher_pipeline: True
ashleys_pipeline: False
hand_selection: False
use_light_data: True
GC_analysis: False
ashleys_threshold: 0.5

# GENECORE
genecore: False
samples_to_process: []
genecore_date_folder: ""
genecore_prefix: "/g/korbel/shared/genecore"

input_bam_legacy: False

### Modes ["count", "segmentation", "mosaiclassifier"]
mode: "mosaiclassifier"
### Plot enabled [True] or disabled [False]
plot: False
### Enable / Disable comparison for each BAM file between folder name & SM tag
check_sm_tag: True
### Enable / Disable download of BAM examples (RPE-BM510)
dl_bam_example: False
### Enable / Disable download of external files (1000G SNV & Fasta ref genome)
dl_external_files: False

normalized_counts: True

## Input BAM location
data_location: ".tests/data_CHR17"
## Output location
# output_location: ".tests/output_CHR17"

reference: "hg38"

references_data:
  "hg38":
    reference_fasta: ".tests/external_data/chr17.fa"
    R_reference: "BSgenome.Hsapiens.UCSC.hg38"
    segdups: "workflow/data/segdups/segDups_hg38_UCSCtrack.bed.gz"
    # snv_sites_to_genotype: ".tests/external_data/1000G_chr21.vcf.gz"
    snv_sites_to_genotype: ""

# Chromosomes list to process
chromosomes:
  - chr17

##############################
# Advanced configuration.  #
##############################

samples: "config/samples.tsv"

# # Enable conda & singularity usage
# use-conda: True
# use-singularity: True
# containerized: True
# singularity-args: "-B /g:/g"
# latency-wait: 60

# Default conda frontend
# conda-frontend: "conda"


# Print shell commands
# printshellcmds: True

# External static data
# R Ref
R_reference: "BSgenome.Hsapiens.UCSC.hg38"
# SegDups file
segdups: "workflow/data/segdups/segDups_hg38_UCSCtrack.bed.gz"

# Exclude cells
exclude_list: []

# Strandphaser
git_commit_strandphaser: "69c9fb4"
git_repo_strandphaser: "https://github.com/daewoooo/StrandPhaseR"
paired_end: True

# CHECKME : Parameters optimization ?
# PARAMETERS

## WINDOW
window: 200000

## METHODS
# methods:
#   - "simpleCalls_llr4_poppriorsTRUE_haplotagsTRUE_gtcutoff0_regfactor6_filterFALSE"
#   - "simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE"

llr: 4
poppriors: TRUE
haplotags:
  - TRUE
  - FALSE
gtcutoff:
  - 0
  - 0.05
regfactor: 6
filter:
  - TRUE
  - FALSE

## BPDENS
### JOINT SEG
min_diff_jointseg: 0.1
### SINGLE SEG
min_diff_singleseg: 0.5
### SCE CUTOFF
additional_sce_cutoff: 20000000
### SCE MIN DISTANCE
sce_min_distance: 500000

abs_path: "/"

## Methods dictionnary
methods:
  lenient:
    method_name: "simpleCalls_llr4_poppriorsTRUE_haplotagsTRUE_gtcutoff0_regfactor6_filterFALSE"
    llr: 4
    poppriors: TRUE
    haplotags: TRUE
    gtcutoff: 0
   regfactor: 6
    filter: "FALSE"

  stringent:
    method_name: "simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE"
    llr: 4
    poppriors: TRUE
    haplotags: TRUE
    gtcutoff: 0.05
    regfactor: 6
    filter: "TRUE"

plottype_consistency:
  - "byaf"
  - "bypos"

plottype_clustering:
  - "position"
  # - "chromosome"
```

### Relevant log output

```shell
Config file config/config.yaml is extended by additional config specified via the command line.                                                                        
Building DAG of jobs...                                                                                                                                                
Conda environment https://github.com/snakemake/snakemake-wrappers/raw/v1.7.0/bio/bwa/index/environment.yaml will be created.                                           
Conda environment https://github.com/snakemake/snakemake-wrappers/raw/v1.7.0/bio/fastqc/environment.yaml will be created.                                              
Conda environment https://github.com/friendsofstrandseq/ashleys-qc-pipeline/raw/1.3.5/workflow/envs/ashleys_rtools.yaml will be created.                               
Conda environment https://github.com/friendsofstrandseq/ashleys-qc-pipeline/raw/1.3.5/workflow/envs/ashleys_base.yaml will be created.                                 
Traceback (most recent call last):                                                                                                                                     
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 730, in snakemake                                      
    success = workflow.execute(                                                                                                                                        
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1033, in execute                                       
    logger.run_info("\n".join(dag.stats()))                                                                                                                            
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/dag.py", line 2414, in stats                                              
    yield tabulate(rows, headers="keys")                                                                                                                               
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate                                       
    list_of_lists, headers = _normalize_tabular_data(                                                                                                                  
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data                        
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))                                                                                         
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>    
 rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/administrator/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/rules.py", line 1222, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

### Anything else?

Downgrading tabluate to 8.10 immediately restores the expected behaviour. Enforcing either this or using Snakemake 7.15.2 should prevent this issue in future

**Comment by weber8thomas** [comment]
Thanks @karen-Gg and sorry not following up on that!
